services:
  api-gateway:
    image: ${REGISTRY}/${REPO_OWNER}/transcription-platform-api-gateway:${IMAGE_TAG}
    build: null

  frontend:
    image: ${REGISTRY}/${REPO_OWNER}/transcription-platform-frontend:${IMAGE_TAG}
    build: null

  auth-service:
    image: ${REGISTRY}/${REPO_OWNER}/transcription-platform-auth-service:${IMAGE_TAG}
    build: null

  upload-service:
    image: ${REGISTRY}/${REPO_OWNER}/transcription-platform-upload-service:${IMAGE_TAG}
    build: null

  call-service:
    image: ${REGISTRY}/${REPO_OWNER}/transcription-platform-call-service:${IMAGE_TAG}
    build: null

  transcription-service:
    image: ${REGISTRY}/${REPO_OWNER}/transcription-platform-transcription-service:${IMAGE_TAG}
    build: null
